name: Custom Action Example

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch
  workflow_dispatch:  # Allows manual triggering of the action

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 23f3004246@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Print date and time
        run: date
