name: Custom Action Example

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch
  workflow_dispatch:  # Allows manual triggering of the action

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: 23f3004246@ds.study.iitm.ac.in
        run: echo "Hello, world!"
