
 name: Test Action

 on:
   push:
     branches:
       - main  # or any branch you want to trigger the action

 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: 23f3004246@ds.study.iitm.ac.in  # This matches the email in your request
         run: echo "Hello, world!"

